name: Build
on:
  workflow_dispatch:

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Установка системных зависимостей
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libssl-dev libsqlite3-dev libffi-dev libexpat1-dev
          pip install --user --upgrade buildozer "cython<3.0.0" virtualenv

      # Кэширование для ускорения процессов
      - name: Cache Buildozer
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            .buildozer
          key: buildozer-ubuntu-${{ github.sha }}
          restore-keys: |
            buildozer-ubuntu-

      # Сборка приложения: мы убрали отдельный шаг лицензий и зашили автосогласие прямо в команду Buildozer!
      - name: Build with Buildozer
        run: |
          cd test_app
          export PATH=$PATH:$HOME/.local/bin
          buildozer android clean
          # Флаг --accept-sdk-license заставит сам Buildozer принять лицензии Google автоматически
          buildozer android debug --accept-sdk-license

      # Скачивание готового файла APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: test_app/bin/*.apk
